### ISSUE TITLE
Uncaught Error: Offset is out of bounds

### ISSUE THREAD

**Issue by renkun-ken** [mark-hahn/view-tail-large-files#6] opened 2014-12-18 01:54 UTC
I open a 43MB tabbed txt file but encounter the following error:

```
fs.js:485
Hide Stack Trace
Error: Offset is out of bounds
  at Error (native)
  at Object.fs.read (fs.js:485:11)
  at oneRead (c:\Users\Kun\.atom\packages\view-tail-large-files\lib\file-reader.coffee:45:12)
  at c:\Users\Kun\.atom\packages\view-tail-large-files\lib\file-reader.coffee:78:13
  at Object.wrapper [as oncomplete] (fs.js:482:17)
```

**Comment by mark-hahn** [comment] 2015-01-29 22:18
Over a month old.  Closing.

**Closed by mark-hahn** 2015-01-29 22:18 UTC

**Comment by tsl0922** [comment] 2015-02-01 08:25
Same here, I'm using Mac OS X 10.10.2:

```
Error: Offset is out of bounds
  at Error (native)
  at Object.fs.read (fs.js:485:11)
  at oneRead (/Users/tsl0922/.atom/packages/view-tail-large-files/lib/file-reader.coffee:56:12)
  at /Users/tsl0922/.atom/packages/view-tail-large-files/lib/file-reader.coffee:89:13
  at Object.wrapper [as oncomplete] (fs.js:482:17)
```

**Comment by mark-hahn** [comment] 2015-02-01 20:23
Is it possible that the file you were looking at was deleted or shrunk in
size?  I have always us it with log files that don't do that.

**Comment by kingslay** [comment] 2015-03-01 15:20
Same here,  I'm using Mac OS X 10.10.3, 
fs.js:536
Hide Stack Trace
Error: Offset is out of bounds
  at Error (native)
  at Object.fs.read (fs.js:536:11)
  at oneRead (/Users/king/.atom/packages/view-tail-large-files/lib/file-reader.coffee:56:12)
  at /Users/king/.atom/packages/view-tail-large-files/lib/file-reader.coffee:89:13
  at FSReqWrap.wrapper [as oncomplete] (fs.js:530:17)
@mark-hahn

**Comment by mark-hahn** [comment] 2015-03-01 20:11
Can you two tell me a little about what you were doing?  Was the file open
somewhere else?  Could it have been modified at the same time you were
viewing it?

**Comment by kingslay** [comment] 2015-03-02 01:41
I open a 3.4MB file。the file not open somewhere else. the attachment is the file. 

> 在 2015年3月2日，上午4:11，mark-hahn <notifications@github.com> 写道：
> 
> Can you two tell me a little about what you were doing? Was the file open
> somewhere else? Could it have been modified at the same time you were
> viewing it?
>

**Comment by mark-hahn** [comment] 2015-03-03 23:30
The attachment didn't work.  Can you send the file to mark@hahnca.com?
Thanks for the trouble.

**Comment by lookitsatravis** [comment] 2015-03-27 22:32
+1 Also having this on several different files. I've tried large .jpg files as well as .pdfs in which I'm trying to view meta data.

**Comment by mark-hahn** [comment] 2015-03-27 22:38
It will not work on binary files like .pdfs and .jpegs.  It can only
display text.  I think this is in the readme.  It uses node buffer routines
to tell the actual char counts on each line.

Sorry.

**Comment by mpwalkerdine** [comment] 2015-03-31 20:02
+1 In my case the log file is being truncated when the application restarts. It would be awesome if this package could handle that use case (I speculate it is reasonably common, especially during development?).

P.S. I really appreciate all the great work you're doing on Atom. Thanks!

**Comment by mark-hahn** [comment] 2015-03-31 20:06
i should be able to handle simple truncation.  I'll put it on my list.

The problem is if the length of a line changes in the middle.  Then my
index is kaput.  I guess detecting a change and then re-indexing the whole
thing would work.  There would be the normal loading delay.  It would be
the same as exiting and reloading but would happen automatically.

**Comment by mpwalkerdine** [comment] 2015-03-31 22:03
Brilliant, sounds good to me. It isn't so hard to close and reopen, just one of those minor inconveniences...

**Comment by mark-hahn** [comment] 2015-03-31 22:05
Are you by any chance from the UK?  I watch UK TV (tellie) and I hear
"brilliant" all the time.

**Comment by mpwalkerdine** [comment] 2015-03-31 23:27
:bowtie: I didn't realise it was idiomatically British...

**Comment by fopina** [comment] 2015-05-19 13:49
This still happens, I'm using version 0.1.14 on OSX with Atom 0.198.0

I'm unable to share the file I'm trying to open, but I'll try to produce a sample.

In the meantime, I've debugged and found what I think might the problem (but unsure how to solve :)).

In the first call of `oneRead`, at this point:

        fs.read fd, buf, bufEnd, bufSize - bufEnd, bytesReadTotal, (err, bytesRead) =>

bufEnd = 0
bufSize = 32768
bytesReadTotal = 0
bytesRead returns 32768

During this first call, however, `bufPos` gets set to 32785.  
So, in the next `oneRead`, `bufEnd` is set to -17 (`bufEnd -= bufPos`) and `fs.read` breaks with outOfBounds:

        fs.read fd, buf, bufEnd, bufSize - bufEnd, bytesReadTotal, (err, bytesRead) =>

bufEnd = -17
bufSize = 32768

So it'll try to read bufSize + 17 when buf only has capacity for bufSize...

I've modified

    if bufPos isnt 0
          buf.copy buf, 0, bufPos, bufEnd
          bufEnd -= bufPos
          # fix attempt begin
          if bufEnd < 0
            bufEnd = 0            
          # fix attempt end
          bufPos = 0

But it doesn't feel like the proper fix (not the lines are properly represented in the editor)..

I hope this helps somehow..

**Comment by fopina** [comment] 2015-05-19 14:41
Ok, so I've found the actual problem...

The file I'm loading is not UTF8 (but does have diacritics)

    $ file asheet.tsv 
    asheet.tsv: ISO-8859 text

And this line:

    str = buf.toString 'UTF8', bufPos, bufEnd

Seems to be the guilty one.  
It forces the conversion to UTF8 which generates more bytes than are actually in the file, resulting in negative `bufEnd` values...

I simply switched `UTF8`to `ASCII` (I haven't searched which possible values are there) and it works neatly (with block character for diacritics).

I guess some sort of fileEncoding should be used here instead...

**Comment by mark-hahn** [comment] 2015-05-19 19:05
Thank you very much.  I'm going through all my packages now so I'll do a
smarter fix soon.
